## Basic Functions

In [1]:
import numpy as np

In [2]:
arr = np.arange(1000000)

In [3]:
pythlist = list(range(1000000))

In [4]:
%time for _ in range(10): [item*3 for item in pythlist]

Wall time: 2.07 s


In [5]:
%time for _ in range(10): arr = arr*3

Wall time: 54 ms


In [6]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1 = np.array([[12,34,45,56,67],[90,98,87,76,65]])
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[[12 34 45 56 67]
 [90 98 87 76 65]]


In [8]:
arr1.shape

(2, 5)

In [9]:
arr1.dtype

dtype('int32')

In [10]:
arr1 = np.array([[12,34,45,56,67],[1.9,98,87,76,65]])
arr1.dtype

dtype('float64')

In [11]:
arr1 = np.array([[12,34,45,56,67],[1.9,98,87,76,65]], dtype='int32')
arr1.dtype

dtype('int32')

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(6).dtype

dtype('float64')

In [16]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr1

array([[12, 34, 45, 56, 67],
       [ 1, 98, 87, 76, 65]])

In [18]:
arr1 * arr1

array([[ 144, 1156, 2025, 3136, 4489],
       [   1, 9604, 7569, 5776, 4225]])

In [19]:
arr1 + arr1

array([[ 24,  68,  90, 112, 134],
       [  2, 196, 174, 152, 130]])

In [20]:
arr1 ** arr1

array([[ -251658240,           0, -1714755555,           0,   882693595],
       [          1,           0, -1465220441,           0,  1526861889]],
      dtype=int32)

In [21]:
3**3

27

In [22]:
np.array([12 ** 12])

array([8916100448256], dtype=int64)

In [23]:
np.array([12.0 ** 12])

array([8.91610045e+12])

In [24]:
1/arr1

array([[0.08333333, 0.02941176, 0.02222222, 0.01785714, 0.01492537],
       [1.        , 0.01020408, 0.01149425, 0.01315789, 0.01538462]])

## Slicing

In [25]:
arr1

array([[12, 34, 45, 56, 67],
       [ 1, 98, 87, 76, 65]])

In [26]:
arr1[4:6]

array([], shape=(0, 5), dtype=int32)

In [27]:
arr2 = np.array([5,4,64,3,8,9,5,3])

In [28]:
arr2[4:6]

array([8, 9])

In [29]:
arr0 = arr2[4:6]

In [30]:
arr0

array([8, 9])

In [31]:
arr0[0]=9

In [32]:
arr2 

array([ 5,  4, 64,  3,  9,  9,  5,  3])

In [33]:
arr9 = arr2[4:6].copy()

In [34]:
arr9

array([9, 9])

In [35]:
arr9[0]=8

In [36]:
arr9

array([8, 9])

In [37]:
arr2

array([ 5,  4, 64,  3,  9,  9,  5,  3])

In [38]:
arr1

array([[12, 34, 45, 56, 67],
       [ 1, 98, 87, 76, 65]])

In [39]:
arr1[0]

array([12, 34, 45, 56, 67])

In [40]:
arr1[0,3]

56