In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]])

In [3]:
myarr

array([[ 3,  6, 32,  7]])

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int32')

In [6]:
myarr[0,1]=2

In [7]:
myarr

array([[ 3,  2, 32,  7]])

## Array creation

### 1. Conversion from other Python structures (i.e. lists and tuples)

In [8]:
listarray = np.array([[1,2,3],[4,5,6],[8,9,0]])

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({3,5,5})

array({3, 5}, dtype=object)

### 2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,5,12)

In [19]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [20]:
lspace = np.linspace(1,4,4)

In [21]:
lspace

array([1., 2., 3., 4.])

In [22]:
emp = np.empty((4,6))

In [23]:
emp

array([[2.39853892e-308, 5.72055370e-278,             nan,
        1.34702330e+165, 5.26143277e-037, 1.02291254e+166],
       [5.02634826e-037, 2.16385190e+190, 3.92188511e-062,
        2.19368135e-056, 1.73686732e-047, 2.14222498e+160],
       [4.30622356e-096, 7.69165785e+218, 1.14428494e+243,
        3.97062388e+246, 1.16318408e-028, 7.32117512e+169],
       [9.33124111e+164, 1.59922459e+160, 1.20913691e+161,
        3.83819517e+151, 1.47721841e+179, 8.37404147e+242]])

In [24]:
emp_like = np.empty_like(lspace)

In [25]:
emp_like

array([1., 2., 3., 4.])

In [26]:
ide = np.identity(45)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

In [29]:
arr = np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr = arr.reshape(3,33)

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr = arr.ravel()

In [34]:
arr.shape

(99,)

## Axis

In [35]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [36]:
ar = np.array(x)

In [37]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
ar.sum(axis=0)

array([12,  8,  9])

In [39]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [40]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [41]:
ar.flat

In [42]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [43]:
ar.ndim

2

In [44]:
ar.size

9

In [45]:
ar.nbytes

36

In [46]:
one = np.array([1,3,4,634,2])

In [47]:
one.argmax()

3

In [48]:
one.argmin()

0

In [49]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int32)

In [50]:
ar.argmin()

8

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
ar.argmax()

6

In [53]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int32)

In [54]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int32)

In [55]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [56]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int32)

In [57]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [58]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [61]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [62]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [63]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [64]:
ar.sum()

29

In [65]:
ar.max()

7

In [66]:
np.where(ar>5)

(array([1, 2], dtype=int32), array([2, 0], dtype=int32))

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
np.count_nonzero(ar)

8

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int32))

In [70]:
ar[1,2] = 0

In [71]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int32))

In [72]:
import sys

In [73]:
py_ar = [0,4,55,2]

In [74]:
np_ar = np.array(py_ar)

In [75]:
sys.getsizeof(1)*len(py_ar)

56

In [76]:
np_ar.itemsize * np_ar.size

16

In [77]:
np_ar.tolist()

[0, 4, 55, 2]